apiVersion: apps/v1
kind: Deployment
metadata:
  name: drink
  labels:
    app: drink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drink
  template:
    metadata:
      labels:
        app: drink
    spec:
      containers:
      - name: drink 
        image: 496278789073.dkr.ecr.ap-northeast-2.amazonaws.com/skteam04/drink:v1 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: '/actuator/health'
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: '/actuator/health'
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: logs 
          mountPath: /logs
      volumes:
      - name: logs 
        persistentVolumeClaim:
          claimName: logs 
